
# Site settings
#title: Fab14 - Education
#tagline: Cruz
#description: > # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

port: 8000
# Plugins
#gems: ["jekyll-paginate"]

#plugins:
 # - jekyll-multiple-languages-plugin
  # - jekyll-feed  
  # - jekyll-paginate


languages: ["fr", "en", "de", "es"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: fr
languageNames:
  fr: Français  
  en: English
  de: Deutsch
  es: Español
  


# Build settings
markdown: kramdown

sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"

permalink: pretty    

exclude:
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - .DS_Store

