#-------------------------------
# General Site Settings of Fab Education
#-------------------------------

title: Fab14 Education
description: Apprentissage et résilience des territoires
email: xxx@xxx.fr

